version: '3.11'

services:
  redis:
    image: redis
    container_name: redis

  db:
    env_file: settings.env
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: postgres_db

  app:
    env_file: settings.env
    build: .
    volumes:
      - .:/django
    ports:
      - "8005:8005"
    image: app:django
    container_name: django_app
#    command: python manage.py runserver 0.0.0.0:8005
    command: sh entrypoint.sh
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: .
    command: celery -A laid_out worker -l INFO
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - db
      - redis
      - app