version: '3.11'
name: laid-out

services:
  redis:
    image: redis
    container_name: redis

  db:
    env_file: settings.env
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: postgres-db

  app:
    env_file: settings.env
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: app:django
    container_name: django-app
    command: sh entrypoint.sh
    depends_on:
      - db

  celery:
    restart: unless-stopped
    build:
      context: .
    command: celery -A laid_out worker -l INFO -E
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - db
      - redis
      - app

  flower:
    env_file: settings.env
    restart: unless-stopped
    build:
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=laid_out.settings
    command: celery -A laid_out.celery.app  flower --logging=info
    volumes:
      - .:/django
    ports:
      - "5555:5555"
    container_name: flower
    depends_on:
      - celery