version: '3'

volumes:
  laid_out_local_postgres_data: { }
  laid_out_local_postgres_data_backups: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: laid_out_local_django
    container_name: laid_out_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.allauth
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: laid_out_production_postgres
    container_name: laid_out_local_postgres
    volumes:
      - laid_out_local_postgres_data:/var/lib/postgresql/data
      - laid_out_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: laid_out_local_docs
    container_name: laid_out_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./laid_out:/app/laid_out:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: laid_out_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: redis:latest
    container_name: laid_out_local_redis

  celeryworker:
    <<: *django
    image: laid_out_local_celeryworker
    container_name: laid_out_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: laid_out_local_celerybeat
    container_name: laid_out_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: [ ]
    command: /start-celerybeat

  flower:
    <<: *django
    image: laid_out_local_flower
    container_name: laid_out_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  vite:
    build:
      context: .
      dockerfile: ./compose/local/vite/Dockerfile
    image: laid_out_local_vite
    volumes:
      - .:/app:z
      - /app/node_modules
    container_name: laid_out_local_vite
    ports:
      - "5173:5173"
