networks:
  web:
    external: true
  internal:
    external: false

volumes:
  production_postgres_data: { }
  production_postgres_data_backups: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: laid_out_production_django
    container_name: laid-out_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
      - ./.envs/.production/.allauth
    command: /start
    networks:
      - web
      - internal

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: laid_out_production_postgres
    container_name: laid-out_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - internal

  redis:
    image: redis:6
    container_name: laid-out_redis
    networks:
      - internal

  celeryworker:
    <<: *django
    image: laid_out_production_celeryworker
    container_name: laid-out_celeryworker
    command: /start-celeryworker
    networks:
      - internal

  celerybeat:
    <<: *django
    image: laid_out_production_celerybeat
    container_name: laid-out_celerybeat
    command: /start-celerybeat
    networks:
      - internal

#  flower:
#    <<: *django
#    image: laid_out_production_flower
#    container_name: laid-out_flower
#    command: /start-flower
#    networks:
#      - web
#      - internal

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    container_name: laid-out_awscli
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z
    networks:
      - internal
