# solo works

volumes:
  production_postgres_data: { }
  production_postgres_data_backups: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: laid_out_production_django
    container_name: laid_out_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
      - ./.envs/.production/.allauth
    command: /start
    networks:
      - traefik-public
      - default

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: laid_out_production_postgres
    container_name: laid_out_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:6
    container_name: laid_out_redis

  celeryworker:
    <<: *django
    image: laid_out_production_celeryworker
    container_name: laid_out_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: laid_out_production_celerybeat
    container_name: laid_out_celerybeat
    command: /start-celerybeat

  # flower:
  #   <<: *django
  #   image: laid_out_production_flower
  #   command: /start-flower

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z

networks:
  traefik-public:
    external: true
  default:
