# Generated by Django 4.2.7 on 2023-12-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=36, verbose_name="Name of User"),
        ),
    ]
