# Generated by Django 4.2.7 on 2023-12-02 19:42

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import laid_out.anxiety.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnxietyTree",
            fields=[
                ("tree_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tree_name", models.CharField(blank=True, default="New Tree", max_length=50, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date")),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "tree_data",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(
                            blank=True, default=laid_out.anxiety.models.default_tree_node, null=True
                        ),
                        default=laid_out.anxiety.models.default_tree_data,
                        size=None,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anxiety_trees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anxiety Tree",
                "verbose_name_plural": "Anxiety Trees",
            },
        ),
    ]
