# Generated by Django 4.2.8 on 2023-12-16 12:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import laid_out.gratitude.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GratitudeJournal",
            fields=[
                (
                    "g_journal_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("g_journal_name", models.CharField(blank=True, default="New Gratitude", max_length=50, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date")),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "g_journal_data",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(default=str),
                        default=laid_out.gratitude.models.default_g_journal_data,
                        size=None,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gratitude_journals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gratitude Journal",
                "verbose_name_plural": "Gratitude Journals",
            },
        ),
    ]
