# Generated by Django 4.2.16 on 2024-12-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gratitude", "0002_alter_gratitudejournal_g_journal_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gratitudejournal",
            name="g_journal_name",
            field=models.CharField(blank=True, default="New Gratitude", max_length=255, null=True),
        ),
    ]
