# Generated by Django 4.2.8 on 2023-12-16 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "journal_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("journal_name", models.CharField(blank=True, default="New Journal", max_length=50, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date")),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("journal_data", models.TextField(blank=True, default=str, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
            },
        ),
    ]
