# Generated by Django 4.2.16 on 2024-12-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="journal_name",
            field=models.CharField(blank=True, default="New Journal", max_length=255, null=True),
        ),
    ]
